steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/recipes', '.']
   dir: 'recipes'
# - id: "init"
#   name: 'hashicorp/terraform:1.0.0'
#   args: ['init']
#   dir: 'terraform'
# - id: "plan"
#   name: 'hashicorp/terraform:1.0.0'
#   args: ['apply','-var=project_id=$PROJECT_ID','-auto-approve']
#   dir: 'terraform'
options:
  logging: CLOUD_LOGGING_ONLY
