steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ["build", "-t", "gcr.io/$PROJECT_ID/recipes:latest", "."]
   dir: 'recipes'
 - name: 'gcr.io/cloud-builders/docker'
   args: ["push", "gcr.io/$PROJECT_ID/recipes:latest"]
   dir: 'recipes'  
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   args: ['gcloud', 'beta', 'build', 'triggers', '--project=${PROJECT}', 'run', 'terraform', '--branch', "${BRANCH_NAME}"]
  #  gcloud beta builds triggers run --project=PROJECT_ID
# images: ["gcr.io/$PROJECT_ID/recipes"]
options:
  logging: CLOUD_LOGGING_ONLY
