steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ["build", "-t", "gcr.io/$PROJECT_ID/recipes:latest", "."]
   dir: 'recipes'
 - name: 'gcr.io/cloud-builders/docker'
   args: ["push", "gcr.io/$PROJECT_ID/recipes:latest"]
   dir: 'recipes'  
  #  gcloud beta builds triggers run --project=PROJECT_ID
# images: ["gcr.io/$PROJECT_ID/recipes"]
options:
  logging: CLOUD_LOGGING_ONLY
