steps:
- name: 'bash'
  id: 'echo'
  args: ['echo', '$PROJECT_ID']  
- name: gcr.io/$PROJECT_ID/snykbuild:0.1
  args: ['sh', '-c', "snyk iac test --json --severity-threshold=high  > /workspace/report$$(date '+%d-%m-%Y').txt"]
  dir: 'terraform'      
  secretEnv: ['SNYK_TOKEN']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['sh', '-c','echo $${PROJECT_ID} && cp /workspace/report*.txt gs://$${PROJECT_ID}_example/']  
  env: 
  - 'PROJECT_ID=$PROJECT_ID'
- id: "init"
  name: 'gcr.io/$PROJECT_ID/terraformbuild:0.1'
  args: ['init']
  dir: 'terraform'
- id: "plan"
  name: 'gcr.io/$PROJECT_ID/terraformbuild:0.1'
  args: ['apply','-var=project_id=$PROJECT_ID','-auto-approve']
  dir: 'terraform'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/snyk-token/versions/1
    env: 'SNYK_TOKEN'
