steps:
- name: 'bash'
  id: 'echo'
  args: ['echo', '$PROJECT_ID']  
- name: gcr.io/$PROJECT_ID/snykbuild:0.1
  args: ['snyk', 'iac', 'test', '--json']
  dir: 'terraform'      
  secretEnv: ['SNYK_TOKEN']
- id: "init"
  name: 'gcr.io/$PROJECT_ID/terraformbuild:0.1'
  args: ['init']
  dir: 'terraform'
- id: "plan"
  name: 'gcr.io/$PROJECT_ID/terraformbuild:0.1'
  args: ['apply','-var=project_id=$PROJECT_ID','-auto-approve']
  dir: 'terraform'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/snyk-token/versions/1
    env: 'SNYK_TOKEN'
