steps:
- name: 'bash'
  args: ['pwd']
- id: "init"
  name: 'hashicorp/terraform:1.0.0'
  args: ['init']
- id: "plan"
  name: 'hashicorp/terraform:1.0.0'
  args: ['plan']
options:
  logging: CLOUD_LOGGING_ONLY
