steps:
- id: "pwd"
  name: 'bash'
  args: ['pwd']
- name: 'bash'
  id: 'ls'
  args: ['ls']  
- id: "init"
  name: 'hashicorp/terraform:1.0.0'
  args: ['init']
- id: "plan"
  name: 'hashicorp/terraform:1.0.0'
  args: ['plan']
options:
  logging: CLOUD_LOGGING_ONLY
