steps:
- name: 'bash'
  id: 'echo'
  args: ['echo', '$PROJECT_ID']  
- name: 'bash'
  id: 'ls'
  args: ['ls',"-R"]  
  dir: 'terraform'
- id: "init"
  name: 'gcr.io/$PROJECT_ID/terraformbuild:0.1'
  args: ['init']
  dir: 'terraform'
- id: "plan"
  name: 'gcr.io/$PROJECT_ID/terraformbuild:0.1'
  args: ['apply','-var=project_id=$PROJECT_ID','-auto-approve']
  dir: 'terraform'
options:
  logging: CLOUD_LOGGING_ONLY
